# Generated by Django 4.0.6 on 2022-09-17 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooking',
            name='p_id',
        ),
    ]
