# Generated by Django 4.0.6 on 2022-09-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_cooking_p_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooking',
            name='backgroundColor',
            field=models.CharField(max_length=7),
        ),
    ]
